# Generated by Django 5.0.6 on 2024-06-28 13:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('service', models.CharField(choices=[('B', 'Blowout'), ('WCS', 'Womens Cut & Style'), ('WMC', 'Womens Master Cut & Style'), ('MCW', 'Mens Wash & Scissor Cut'), ('LMC', 'Lengthy Master Color'), ('BMC', 'Buzz Master Color'), ('F', 'Fix Your Face'), ('FF', 'Face First')], default='B', max_length=3)),
                ('stylists', models.CharField(choices=[('A', 'Annabelle'), ('C', 'Corey'), ('D', 'Devlin'), ('G', 'Giang'), ('S', 'Scott')], default='A', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('cost', models.IntegerField(verbose_name=0)),
                ('parent_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
