# Generated by Django 5.0.6 on 2024-06-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service_date_service_parent_service_service_stylists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
    ]
